name: Labeler
on: 
  push:
    branches:
      - 'main'

jobs:
  comment-on-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get commits
        id: get-commits
        run: |
          const { context, github } = require('@actions/github');

          async function getCommits() {
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const pull_number = context.payload.number;
            const { data } = await github.rest.pulls.listCommits({
              owner,
              repo,
              pull_number,
            });
            return data.map((commit) => commit.commit.message);
          }

      - name: Comment on PR
        run: |
          const { context, github } = require('@actions/github');

          const comment = 'O problema #123 foi corrigido.';
          const { data: commentData } = await github.rest.issues.createComment({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            issue_number: context.payload.number,
            body: comment,
          });
          console.log(`Comentário criado: ${commentData.html_url}`);

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
