name: Labeler
on: 
  push:
    branches:
      - 'main'

jobs:
  comment-on-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install @actions/github

      - name: Labeler
        run: node .github/scripts/labeler.js

        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
