name: Labeler
on: 
  push:
    branches:
      - 'main'
      - 'teste'

jobs:
  comment-on-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install

      - name: Labeler
        run: node .github/scripts/labeler.js

        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
